Handling Imbalanced Dataset

1.Up Sampling
2.Down Sampling

In [5]:
import numpy as np
import pandas as pd

#Set the random seed for reproductibility
np.random.seed(123)

#Create a datafram with two classes

n_samples=1000
class_0_ratio=0.9
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples - n_class_0

In [6]:
n_class_0,n_class_1

(900, 100)

In [7]:

## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [11]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [13]:
df.head()
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [15]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [16]:
## Upsampling

df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [ ]:
from sklearn.utils import resample
df_minority_upsample = resample(
         df_minority,
         replace=True,
         n_samples=len(df_majority),
         random_state=42)

'''replace=True → allows the same row to be picked multiple times (sampling with replacement).

      Without this, you couldn’t make the minority as big as the majority, since you’d run out of rows.

n_samples=len(df_majority) → makes the minority class as big as the majority class.

      Example: if majority has 900 rows, this will create 900 minority rows (by repeating them).

random_state=42 → ensures reproducibility (same resampled rows every time you run).'''

'replace=True → allows the same row to be picked multiple times (sampling with replacement).\n\nWithout this, you couldn’t make the minority as big as the majority, since you’d run out of rows.\n\nn_samples=len(df_majority) → makes the minority class as big as the majority class.\n\nExample: if majority has 900 rows, this will create 900 minority rows (by repeating them).\n\nrandom_state=42 → ensures reproducibility (same resampled rows every time you run).'

In [25]:
df_minority_upsample.shape

(900, 3)

In [19]:
df_minority_upsample.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [20]:
df_upsampled = pd.concat([df_majority,df_minority_upsample])

In [23]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [26]:
## Down Sampling

import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [27]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [29]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False, #Sample With replacement
         n_samples=len(df_minority),
         random_state=42
        )

In [30]:
df_majority_downsampled.shape

(100, 3)

In [31]:
df_downsampled = pd.concat([df_minority,df_majority_downsampled])
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64